name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
        - name: my-step
          run: echo "Hello World!" 
        - name: college
          run: echo "Attending Workshop"
        - name: lab
          run: echo "Learn Coding"
        - name: class
          run: echo "seminar"
